name: saytara
description: Nilco Sales Performance App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.0.0
  
  # Networking
  dio: ^5.4.3+1
  
  # Local Storage
  shared_preferences: ^2.2.3
  
  # Localization
  easy_localization: ^3.0.7
  
  # Secure Storage & Sensors
  flutter_secure_storage: ^9.0.0
  sensors_plus: ^5.0.0
  
  # Hardware / Sensors
  image_picker: ^1.1.0
  camera: ^0.10.5+9
  geolocator: ^12.0.0
  confetti: ^0.7.0
  
  # UI & Animations
  lottie: ^3.1.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.67.0
  
  # Env Config
  flutter_dotenv: ^5.1.0

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/l10n/
